# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-CSV
version:      1.02
version_from: CSV.pm
installdirs:  site
requires:
    Class::Accessor:               0.18
    Text::CSV_XS:                  0.23

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
